"""Tests for raster metadata extraction and GeoCard generation (metadata.py)."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from examples.amazon_ndvi import skill as ndvi_skill  # noqa: E402

from geonexus.metadata import inspect_raster, raster_stats, raster_to_geocard  # noqa: E402


@pytest.fixture(scope="module")
def demo_raster(tmp_path_factory: pytest.TempPathFactory) -> str:
    """A real GeoTIFF generated by the demo skill (synthetic, but valid)."""
    out = tmp_path_factory.mktemp("rasters")
    paths = ndvi_skill.generate_synthetic_scene(2015, str(out), width=64, height=64, seed=7)
    return paths["red"]


class TestInspectRaster:
    def test_metadata_shape(self, demo_raster: str) -> None:
        meta = inspect_raster(demo_raster)
        assert meta["driver"] == "GTiff"
        assert meta["width"] == 64
        assert meta["height"] == 64
        assert meta["count"] == 1
        assert meta["dtype"] == "uint16"
        assert meta["crs"] == "EPSG:4326"
        # Amazon bounds.
        w, s, e, n = meta["bounds"]
        assert w == -73.9 and e == -44.0 and s == -15.0 and n == 5.0
        assert len(meta["bands"]) == 1
        assert meta["bands"][0]["dtype"] == "uint16"
        assert meta["resolution"][0] > 0

    def test_missing_file(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError):
            inspect_raster(tmp_path / "nope.tif")


class TestRasterStats:
    def test_stats_computed(self, demo_raster: str) -> None:
        stats = raster_stats(demo_raster)
        assert stats["count"] == 64 * 64
        assert stats["mean"] is not None
        assert stats["mean"] >= 0  # uint16 DN values (scaled reflectance)

    def test_band_out_of_range(self, demo_raster: str) -> None:
        with pytest.raises(ValueError, match="out of range"):
            raster_stats(demo_raster, band=5)


class TestRasterToGeoCard:
    def test_card_generated(self, demo_raster: str) -> None:
        card = raster_to_geocard(demo_raster, name="My dataset", tags=["amazon"], capabilities=["ndvi"])
        assert card.type == "data"
        assert card.name == "My dataset"
        assert "uploaded" in card.tags
        assert "amazon" in card.tags
        assert "GTiff" in card.tags
        # Spatial from actual metadata.
        assert card.spatial is not None
        assert card.spatial.bbox == [-73.9, -15.0, -44.0, 5.0]
        assert card.spatial.crs == "EPSG:4326"
        # Bands from metadata.
        assert len(card.bands) == 1
        assert card.bands[0].dtype == "uint16"
        # Capability declared by uploader.
        assert "ndvi" in [c.name for c in card.capabilities]
        # Access points at the file.
        assert card.access is not None
        assert card.access.protocol == "file"
        assert Path(card.access.endpoint or "").exists()

    def test_card_with_temporal(self, demo_raster: str) -> None:
        card = raster_to_geocard(demo_raster, start="2015-01-01", end="2015-12-31")
        assert card.temporal is not None
        assert card.temporal.start == "2015-01-01"

    def test_custom_id_and_sanitized_default(self, demo_raster: str) -> None:
        card = raster_to_geocard(demo_raster, card_id="my-data-001")
        assert card.id == "my-data-001"

    def test_schema_valid(self, demo_raster: str) -> None:
        card = raster_to_geocard(demo_raster, validate=True)
        from geonexus.geocard.validator import validate_card_schema

        report = validate_card_schema(card.to_dict())
        assert report.valid, report.errors
